# Generated by Django 4.1 on 2022-08-16 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 9, 50, 23, 215002, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
